# Generated by Django 4.2.7 on 2023-12-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('email', models.EmailField(max_length=100, verbose_name='Электронный адрес клиента')),
                ('procedure', models.CharField(max_length=100, verbose_name='Процедура')),
                ('date', models.DateField(verbose_name='Дата записи')),
                ('time', models.TimeField(verbose_name='Время записи')),
                ('newsletter', models.BooleanField(default=True, verbose_name='Рассылка новостей')),
            ],
            options={
                'verbose_name': 'Запись на процедуру',
                'verbose_name_plural': 'Записи на процедуры',
            },
        ),
    ]
