# Generated by Django 4.2.7 on 2023-12-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Электронный адрес '),
        ),
        migrations.AlterField(
            model_name='records',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='records',
            name='newsletter',
            field=models.BooleanField(default=True, verbose_name='Хочу получать рассылку новостей'),
        ),
        migrations.AlterField(
            model_name='records',
            name='procedure',
            field=models.CharField(choices=[('Массаж лица', 'Массаж лица'), ('Биорепарация', 'Биорепарация'), ('Биоревитализация', 'Биоревитализация'), ('Чистка лица', 'Чистка лица'), ('Губы', 'Губы')], max_length=100, verbose_name='Процедура'),
        ),
    ]
