# Generated by Django 4.2.7 on 2023-12-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_procedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена процедуры'),
        ),
    ]
