# Generated by Django 4.2.7 on 2023-12-10 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_procedure_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='main.category'),
        ),
    ]
